### ISSUE TITLE
Would it be possible to port this to Firefox?

### ISSUE THREAD

**Issue by refparo** [machawk1/warcreate#130]

**Comment by machawk1** [comment]
@refparo Yes, it is likely possible but would require some adaptations to WebExtension APIs beyond the deprecated functions like you mentioned in #102. Any further efforts to identify these incompatibilities would be appreciated.

**Comment by machawk1** [comment]
For a bit more completeness, there were initial efforts to do exactly this back when Firefox still used XULs for add-ons, see https://github.com/machawk1/ffwarcreate . WARCreate, the Chrome extension, predates Firefox's move to WebExtensions.

**Comment by LaoshuBaby** [comment]
> For a bit more completeness, there were initial efforts to do exactly this back when Firefox still used XULs for add-ons, see https://github.com/machawk1/ffwarcreate . WARCreate, the Chrome extension, predates Firefox's move to WebExtensions.

Thank you for describe this, but looks like that project didn't released some installable plugin files? 🥹

**Comment by machawk1** [comment]
@LaoshuBaby Indeed, more effort would be needed to first port the codebase to use WebExtensions instead of the `chrome.*` API. In that same effort, we might also push to use Manifest v3 (as Chrome will soon be deprecating v2 extensions). I am uncertain on where Mozilla stands on forcing MV3 on Firefox add-ons.
